[package]
name = "my-dapp"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.13"
[features]
no-entrypoint = []
test-sbf = []
[lib]
crate-type = ["cdylib","lib"]
[dev-dependencies]
solana-program-test = "2.0.13"
solana-sdk = "2.0.13"